# generated by zon2nix (https://github.com/nix-community/zon2nix)

{
  linkFarm,
  fetchzip,
  fetchgit,
}:

linkFarm "zig-packages" [
  {
    name = "babel-0.12.2-zYhD5xqgAQCkH3Ci0nhwAJQYfVoA9WldK7K6VtW-SVbJ";
    path = fetchgit {
      url = "https://github.com/mkindberg/babel/";
      rev = "45abcd557b7f8c17c071e2eeca4d890071c68c09";
      hash = "sha256-M97Z4GH2qELmZJ1XiKk8yjt3BrnbRcDQgqtq+si5U8w=";
    };
  }
]
